/**
 * Filename: CsrfModelAdvice.kt
 * Author: Andrias Zelele
 * Date: 2026-03-03
 *
 * Description:
 * Provides global CSRF token exposure to all Thymeleaf/Mustache views
 * in the YesNoQuest application.
 *
 * This class ensures that the CSRF token generated by Spring Security
 * is automatically added to every model, allowing forms to include
 * the required CSRF hidden field without manually injecting it
 * in each controller.
 *
 * Responsibilities:
 * - Intercepts all controller responses
 * - Extracts the active CSRF token from the request context
 * - Adds the token to the model under the attribute name "_csrf"
 *
 * Security Notes:
 * - CSRF protection is enabled globally in SecurityConfig.
 * - This class makes the token available to frontend templates.
 * - If CSRF is disabled, this will receive null.
 */

package com.dre.yesnoquest.config

import org.springframework.security.web.csrf.CsrfToken
import org.springframework.web.bind.annotation.ControllerAdvice
import org.springframework.web.bind.annotation.ModelAttribute

/**
 * Global controller advice that injects the CSRF token
 * into every model automatically.
 *
 * @ControllerAdvice makes this apply across the entire application.
 */
@ControllerAdvice
class CsrfModelAdvice {

    /**
     * Adds the current CSRF token to the model under the name "_csrf".
     *
     * This allows frontend templates (Mustache/Thymeleaf)
     * to reference the token like:
     *
     * <input type="hidden" name="{{_csrf.parameterName}}" value="{{_csrf.token}}" />
     *
     * @param token The CSRF token generated for the current request.
     * @return The same token, exposed to the model.
     */
    @ModelAttribute("_csrf")
    fun csrfToken(token: CsrfToken?): CsrfToken? = token
}