/**
 * Filename: AppUser.kt
 * Author: Andrias Zelele
 * Date: 2026-03-03
 *
 * Description:
 * JPA entity representing an application user in the YesNoQuest system.
 *
 * This entity maps to the "users" database table and stores
 * authentication credentials and basic login tracking metadata.
 *
 * Responsibilities:
 * - Store unique username
 * - Store hashed password (BCrypt)
 * - Track account creation timestamp
 * - Track last login timestamp
 * - Track total login count
 *
 * Security Notes:
 * - Passwords are NEVER stored in plaintext.
 * - passwordHash must align with BCryptPasswordEncoder.
 * - username is unique at the database level.
 */

package com.dre.yesnoquest.model

import jakarta.persistence.*
import java.time.LocalDateTime

/**
 * Entity representing a registered user account.
 *
 * Mapped to table: "users"
 */
@Entity
@Table(name = "users")
class AppUser(

    /**
     * Primary key.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long? = null,

    /**
     * Unique username for login.
     * Cannot be null.
     */
    @Column(nullable = false, unique = true)
    var username: String = "",

    /**
     * BCrypt-hashed password.
     * Must match encoder configured in SecurityConfig.
     */
    @Column(nullable = false)
    var passwordHash: String? = "",

    /**
     * Timestamp when the account was created.
     * Defaults to current system time.
     */
    @Column(nullable = false)
    var createdAt: LocalDateTime = LocalDateTime.now(),

    /**
     * Timestamp of the most recent successful login.
     * Nullable because user may not have logged in yet.
     */
    var lastLoginAt: LocalDateTime? = null,

    /**
     * Tracks number of successful logins.
     */
    @Column(nullable = false)
    var loginCount: Long = 0
)